### ISSUE TITLE
Failing date test

### ISSUE THREAD

**Issue by birkland** [DataConservancy/pass-ember#40]
Started failing in 5a96688  as part of fix for  #25

**Comment by birkland** [comment]
Travis failures may have revealed a problem whereby printed dates are formatted according to the machine's local time zone, which may not be consistent with the recorded data, or something along those lines.  It seems to be [a bigger issue](http://blog.skylight.io/bringing-sanity-to-javascript-utc-dates-with-moment-js-and-ember-data/) than simply a failing test; it's unclear to me what any of the printed dates actually mean.

Maybe [ember-moment](https://github.com/stefanpenner/ember-moment) can provide a solution?

**Comment by markpatton** [comment]
Ah. Yes. Dates are always fun. I think it can be cleared up.

**Comment by markpatton** [comment]
Fixed travis build in  8db9b3defaf9f62dff7d2e4955b211500f22b633. There was actually a bug in the formatter, but the travis issue was the tests were trying to create Dates in a bad way. Eventually we should look at something like ember-moment.

**Comment by birkland** [comment]
The build seems to start failing for me now (when it gets close to midnight??.  It seemed to be OK earlier in the day; nothing date-related has changed)

    not ok 75 Chrome 63.0 - Integration | Component | date cell: it renders
    ---
        actual: >
            1/19/2010
        expected: >
            1/20/2010
        stack: >
                at Object.<anonymous> (http://localhost:7357/assets/tests.js:556:12)
                at runTest (http://localhost:7357/assets/test-support.js:4071:30)
                at Test.run (http://localhost:7357/assets/test-support.js:4057:6)
                at http://localhost:7357/assets/test-support.js:4263:12
                at Object.advance (http://localhost:7357/assets/test-support.js:3709:26)
                at begin (http://localhost:7357/assets/test-support.js:5530:20)
        Log: |
    ...

**Comment by htpvu** [comment]
I'm having the same issue. took me a while to track it down.

**Comment by markpatton** [comment]
It should be an easy fix. Have to set the utc time as well as date.
